development:
    lang: "pt"
    base: ""
    couchdb: "http://localhost:5984"
    connect: ""
    connect_url: ""
    elasticsearch: ""
    dwc_services: ""
    base_list: "plantas_raras_do_cerrado"
test:
    lang: "pt"
    base: ""
    couchdb: "http://localhost:5984"
    connect: ""
    connect_url: ""
    elasticsearch: ""
    dwc_services: ""
    base_list: "plantas_raras_do_cerrado"
production:
    lang: "pt"
    base: ""
    etcd: ""
    couchdb: ""
    connect: ""
    connect_url: ""
    elasticsearch: ""
    dwc_services: ""
