development:
    lang: "pt"
    base: ""
    couchdb: "http://localhost:5984"
    connect: "http://192.168.50.55:8080"
    connect_url: "http://192.168.50.55:8080"
    elasticsearch: "http://192.168.50.55:9200"
    base_list: "plantas_raras_do_cerrado"
test:
    lang: "pt"
    base: ""
    couchdb: "http://localhost:5984"
    couchdb: "http://localhost:5984"
    connect: "http://192.168.50.55:8080"
    connect_url: "http://192.168.50.55:8080"
    elasticsearch: "http://192.168.50.55:9200"
    base_list: "plantas_raras_do_cerrado"
production:
    lang: "pt"
    base: "/reports2"
    etcd: "http://$HOST/etcd"
    couchdb: "http://$HOST/couchdb"
    connect: "http://$HOST/connect"
    connect_url: "http://$HOST/connect"
    elasticsearch: "http://$HOST/elasticsearch"
