reports2:
    image: cncflora/apache
    ports:
        - 8081:80
    volumes:
        - ../:/var/www
    links:
        - elasticsearch
        - couchdb
        - dwc_services
        - floradata
    environment:
        - PHP_ENV=development
dwc_services:
  image: cncflora/dwc-services
elasticsearch:
    image: cncflora/elasticsearch
    ports:
        - 9200:9200
    volumes:
        - /var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw
couchdb:
    image: cncflora/couchdb
    ports:
        - 5984:5984
    volumes:
        - /var/data/couchdb:/var/lib/couchdb:rw
floradata:
    image: cncflora/floradata
    ports:
        - 8181:80
        - 9005:9001
